### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by zzangoobrother** [jonghyeon1013/Spring#1]
안녕하세요. 과제 하시느라 수고하셨습니다.

1. 클래스명이 전부 Spring으로 시작하시네요. Spring이 맞을까요? 게시글 작성인데 게시글과 관련된 클래스명으로 해야하지 않을까요? 지금은 혼자 과제를 해서 괜찮지만 나중에 팀 프로젝트 하면 클래스명과 메소드명이 중요하게 됩니다. 클래스명을 게시글 관련 역할이 드러나게 수정해주세요.

2. service 클래스에서 클래스 위에 @Transactional 을 하신거는 잘 하셨습니다. 하지만 이는 저장, 수정, 삭제 일때 유용하고 조회일 때는 좋지 않습니다. 왜 좋지 않은지 공부 해보시고 수정해주세요.

3.  service 에 if else 문이 있는데 if else 문은 가독성이 좋지 않아 최대한 사용하지 않는게 좋습니다. 그리고 요즘은 서버가 많이 좋아져 괜찮지만 성능상 좋지 않습니다. 최대한 if 문만 사용하시고 꼭 써야 할 때만 사용해주세요.

과제 하시느라 수고 하셨습니다.

**Comment by jonghyeon1013** [comment]
올려주신 내용 참고하여 다시 한번 해보겠습니다. 감사합니다.

**Comment by jonghyeon1013** [comment]
올려주신 내용 참고하여 다시 한번 해보겠습니다. 감사합니다.
